export const FETCH_ITEMS = 'FETCH_ITEMS';

export const CREATE_CHECK = 'CREATE_CHECK';
export const ADD_TO_CHECK = 'ADD_TO_CHECK';
export const REMOVE_FROM_CHECK = 'REMOVE_FROM_CHECK';
export const GET_OPEN_CHECKS = 'GET_OPEN_CHECKS';
export const LOAD_CURRENT_CHECK = 'LOAD_CURRENT_CHECK';
export const CLEAR_CURRENT_CHECK = 'CLEAR_CURRENT_CHECK';
export const CLEAR_NEW_ITEMS = 'CLEAR_NEW_ITEMS';

export const INCREMENT_COURSE = 'INCREMENT_COURSE';
export const DECREMENT_COURSE = 'DECREMENT_COURSE';
export const INCREMENT_SEAT = 'INCREMENT_SEAT';
export const DECREMENT_SEAT = 'DECREMENT_SEAT';

export const FIRE_COURSE_2 = 'FIRE_COURSE_2';
export const FIRE_COURSE_3 = 'FIRE_COURSE_3';

export const ADD_PAYMENT = 'ADD_PAYMENT';
export const GET_OPEN_PAYMENTS = 'GET_OPEN_PAYMENTS';

export const FETCH_USER = 'FETCH_USER';
export const CLEAR_USER_PIN = 'CLEAR_USER_PIN';

export const GET_DAY_OPEN_TIME = 'GET_DAY_OPEN_TIME';
export const GET_EMPLOYEE_HOURS = 'GET_EMPLOYEE_HOURS';
export const GET_DAY_TOTALS = 'GET_DAY_TOTALS';

export const FETCH_MODS = 'FETCH_MODS';
export const ADD_MOD_TO_ITEM = 'ADD_MOD_TO_ITEM';
