export const FETCH_ITEMS = 'FETCH_ITEMS';
export const CREATE_CHECK = 'CREATE_CHECK';
export const CREATE_ORDER = 'CREATE_ORDER';
export const ADD_TO_CHECK = 'ADD_TO_CHECK';
export const GET_OPEN_CHECKS = 'GET_OPEN_CHECKS';
export const REMOVE_FROM_CHECK = 'REMOVE_FROM_CHECK';
